# Generated by Django 2.1.3 on 2019-03-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50, verbose_name='收货人')),
                ('ads', models.CharField(max_length=300, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=20, verbose_name='收货电话')),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='cart_count', verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('unit', models.CharField(max_length=30, verbose_name='单位')),
                ('picture', models.ImageField(upload_to='media', verbose_name='商品图片')),
                ('detail', models.CharField(default='商品详情', max_length=255, verbose_name='商品详情')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='分类名称')),
                ('desc', models.CharField(default='商品描述', max_length=200, verbose_name='分类描述')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, verbose_name='商品编号')),
                ('orderdetail', models.TextField(verbose_name='订单详情')),
                ('adsname', models.CharField(max_length=30, verbose_name='收件人姓名')),
                ('adsphone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('ads', models.CharField(max_length=300, verbose_name='地址')),
                ('time', models.DateTimeField(auto_now=True)),
                ('acot', models.IntegerField(verbose_name='总数')),
                ('acount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('orderstatus', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='订单')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
                ('isban', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.GoodsType'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='good',
            field=models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='shops.Goods'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
        migrations.AddField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.UserInfo'),
        ),
    ]
